### ISSUE TITLE
BART and T5 Extractive Summarisation

### ISSUE THREAD

**Issue by createmomo** [airKlizz/SummarizationBaselines#2]
Hi, thank you very much for this nice repository.

I noticed that you used the BART and T5 based methods to do extractive summarization. Could you please recommend some links/papers on how to use BART/T5 to do Extractive Summarization? I thought they can only be used for abstractive summarization.

Thank you very much!

**Comment by airKlizz** [comment]
Hi,

Sorry it's a mistake on my part. The repository is still in development and the README.md was not up to date. Bart and T5 are used here to make abstractive summarization.

**Comment by createmomo** [comment]
> Hi,
> 
> Sorry it's a mistake on my part. The repository is still in development and the README.md was not up to date. Bart and T5 are used here to make abstractive summarization.

Hi, 

Thank you for clarifying that. Looking forward to your update! :)

Best wishes,
